//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackingProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTask
    {
        public int EmployeeTaskID { get; set; }
        public int EmployeeID { get; set; }
        public int TaskID { get; set; }
        public int CreatorID { get; set; }
        public string Creator { get; set; }
        public string IssueType { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
