//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackingProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDescription
    {
        public int TaskDescriptionID { get; set; }
        public string TaskDescription1 { get; set; }
        public int TaskID { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
